var app = angular.module('ADEGenreSearchApp', []);

app.controller('searchCtrl', function ($scope, $http) {
    $scope.genres = [
{ name: "tech house", slug: "tech-house" },
{ name: "minimal techno", slug: "minimal-techno" },
{ name: "deeper house", slug: "deeper-house" },
{ name: "progressive house", slug: "progressive-house" },
{ name: "deep disco house", slug: "deep-disco-house" },
{ name: "microhouse", slug: "microhouse" },
{ name: "house", slug: "house" },
{ name: "techno", slug: "techno" },
{ name: "german techno", slug: "german-techno" },
{ name: "big room", slug: "big-room" },
{ name: "progressive electro house", slug: "progressive-electro-house" },
{ name: "dutch house", slug: "dutch-house" },
{ name: "deep euro house", slug: "deep-euro-house" },
{ name: "edm", slug: "edm" },
{ name: "detroit techno", slug: "detroit-techno" },
{ name: "minimal dub", slug: "minimal-dub" },
{ name: "uplifting trance", slug: "uplifting-trance" },
{ name: "trance", slug: "trance" },
{ name: "electro house", slug: "electro-house" },
{ name: "progressive trance", slug: "progressive-trance" },
{ name: "future garage", slug: "future-garage" },
{ name: "bass music", slug: "bass-music" },
{ name: "outsider house", slug: "outsider-house" },
{ name: "disco house", slug: "disco-house" },
{ name: "deep soul house", slug: "deep-soul-house" },
{ name: "tribal house", slug: "tribal-house" },
{ name: "more tech house", slug: "more-tech-house" },
{ name: "dub techno", slug: "dub-techno" },
{ name: "deep house", slug: "deep-house" },
{ name: "vocal house", slug: "vocal-house" },
{ name: "acid house", slug: "acid-house" },
{ name: "hardstyle", slug: "hardstyle" },
{ name: "deep tech house", slug: "deep-tech-house" },
{ name: "chicago house", slug: "chicago-house" },
{ name: "more uplifting trance", slug: "more-uplifting-trance" },
{ name: "dubstep", slug: "dubstep" },
{ name: "more deep house", slug: "more-deep-house" },
{ name: "dutch hip hop", slug: "dutch-hip-hop" },
{ name: "drum and bass", slug: "drum-and-bass" },
{ name: "pop house", slug: "pop-house" },
{ name: "footwork", slug: "footwork" },
{ name: "electroclash", slug: "electroclash" },
{ name: "wonky", slug: "wonky" },
{ name: "minimal melodic techno", slug: "minimal-melodic-techno" },
{ name: "electronic", slug: "electronic" },
{ name: "schranz", slug: "schranz" },
{ name: "re:techno", slug: "re:techno" },
{ name: "nu disco", slug: "nu-disco" },
{ name: "liquid funk", slug: "liquid-funk" },
{ name: "glitch", slug: "glitch" },
{ name: "fidget house", slug: "fidget-house" },
{ name: "destroy techno", slug: "destroy-techno" },
{ name: "progressive psytrance", slug: "progressive-psytrance" },
{ name: "more deeper house", slug: "more-deeper-house" },
{ name: "jump up", slug: "jump-up" },
{ name: "filter house", slug: "filter-house" },
{ name: "jungle", slug: "jungle" },
{ name: "intelligent dance music", slug: "intelligent-dance-music" },
{ name: "electro", slug: "electro" },
{ name: "balearic", slug: "balearic" },
{ name: "acid techno", slug: "acid-techno" },
{ name: "progressive uplifting trance", slug: "progressive-uplifting-trance" },
{ name: "nu jazz", slug: "nu-jazz" },
{ name: "gabba", slug: "gabba" },
{ name: "broken beat", slug: "broken-beat" },
{ name: "breakbeat", slug: "breakbeat" },
{ name: "big beat", slug: "big-beat" },
{ name: "ambient dub techno", slug: "ambient-dub-techno" },
{ name: "trip hop", slug: "trip-hop" },
{ name: "trapstep", slug: "trapstep" },
{ name: "sexy", slug: "sexy" },
{ name: "r-neg-b", slug: "r-neg-b" },
{ name: "neurofunk", slug: "neurofunk" },
{ name: "hard trance", slug: "hard-trance" },
{ name: "chill-out", slug: "chill-out" },
{ name: "acid jazz", slug: "acid-jazz" },
{ name: "synthpop", slug: "synthpop" },
{ name: "post-metal", slug: "post-metal" },
{ name: "pop", slug: "pop" },
{ name: "ninja", slug: "ninja" },
{ name: "new rave", slug: "new-rave" },
{ name: "neurostep", slug: "neurostep" },
{ name: "more progressive house", slug: "more-progressive-house" },
{ name: "moombahton", slug: "moombahton" },
{ name: "glitch hop", slug: "glitch-hop" },
{ name: "electro trash", slug: "electro-trash" },
{ name: "electro latino", slug: "electro-latino" },
{ name: "dutch rock", slug: "dutch-rock" },
{ name: "downtempo", slug: "downtempo" },
{ name: "complextro", slug: "complextro" },
{ name: "ambient", slug: "ambient" },
{ name: "alternative dance", slug: "alternative-dance" },
{ name: "turntablism", slug: "turntablism" },
{ name: "thrash core", slug: "thrash-core" },
{ name: "speed garage", slug: "speed-garage" },
{ name: "sludge metal", slug: "sludge-metal" },
{ name: "shoegaze", slug: "shoegaze" },
{ name: "retro electro", slug: "retro-electro" },
{ name: "old school hip hop", slug: "old-school-hip-hop" },
{ name: "nu gaze", slug: "nu-gaze" },
{ name: "more progressive trance", slug: "more-progressive-trance" },
{ name: "minimal dubstep", slug: "minimal-dubstep" },
{ name: "latvian pop", slug: "latvian-pop" },
{ name: "jumpstyle", slug: "jumpstyle" },
{ name: "indonesian pop", slug: "indonesian-pop" },
{ name: "indietronica", slug: "indietronica" },
{ name: "indie rock", slug: "indie-rock" },
{ name: "illbient", slug: "illbient" },
{ name: "hip house", slug: "hip-house" },
{ name: "hip hop", slug: "hip-hop" },
{ name: "hard house", slug: "hard-house" },
{ name: "hardcore techno", slug: "hardcore-techno" },
{ name: "electro swing", slug: "electro-swing" },
{ name: "dream pop", slug: "dream-pop" },
{ name: "dance-punk", slug: "dance-punk" },
{ name: "dance pop", slug: "dance-pop" },
{ name: "catstep", slug: "catstep" },
{ name: "brostep", slug: "brostep" },
{ name: "bass trip", slug: "bass-trip" },
{ name: "australian dance", slug: "australian-dance" },
{ name: "abstract", slug: "abstract" }
    ];

    $scope.load = function (slug) {
        $scope.template = 'genres/' + slug + '.html';
        console.log($scope.template);
    };
});
